# Generated by Django 5.2.7 on 2025-10-25 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='papel',
            field=models.CharField(choices=[('congregado', 'Congregado'), ('membro', 'Membro'), ('secretario', 'Secretário'), ('professor', 'Professor')], default='congregado', max_length=20, verbose_name='Papel no Sistema'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Curso Ativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horária (horas)')),
                ('professor', models.ForeignKey(limit_choices_to={'papel': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_ministrados', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('observacao_professor', models.TextField(blank=True, verbose_name='Observação do Professor')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_certificado', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_certificado', to='usuarios.curso', verbose_name='Curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_para_aprovar', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Solicitação de Certificado',
                'verbose_name_plural': 'Solicitações de Certificado',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Matrícula')),
                ('concluido', models.BooleanField(default=False, verbose_name='Curso Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('aluno', models.ForeignKey(limit_choices_to={'papel__in': ['membro', 'congregado']}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuarios.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_matricula'],
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
