# Generated by Django 5.2.7 on 2025-10-15 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_youtube', models.URLField(help_text='URL do vídeo do YouTube que será exibido na página principal', max_length=255, verbose_name='Link do YouTube')),
                ('titulo_video', models.CharField(default='Última Transmissão ao Vivo', help_text='Título que será exibido acima do vídeo', max_length=100, verbose_name='Título do Vídeo')),
                ('tipo_imagem', models.CharField(choices=[('capa-ceia', 'Culto de Ceia'), ('capa-divino', 'Culto Divino'), ('capa-ebd', 'EBD'), ('capa-maravilhas', 'Culto das Maravilhas'), ('capa-louvor', 'Culto de Louvor'), ('personalizada', 'Imagem Personalizada (Upload)')], default='capa-maravilhas', help_text="Selecione uma imagem padrão ou escolha 'Imagem Personalizada' para fazer upload", max_length=20, verbose_name='Tipo de Imagem')),
                ('imagem_personalizada', models.ImageField(blank=True, help_text="Faça upload de uma imagem personalizada (apenas se 'Tipo de Imagem' for 'Imagem Personalizada')", null=True, upload_to='uploads/capas/', verbose_name='Imagem Personalizada')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('descricao', models.TextField(blank=True, help_text='Uma breve descrição do departamento.', verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Imagem representativa do departamento.', upload_to='departamentos/', verbose_name='Imagem')),
                ('categoria', models.CharField(choices=[('TREINAMENTO', 'Ministério de Treinamento e Crescimento Cristão'), ('MUSICA', 'Ministério de Música')], max_length=50, verbose_name='Ministério Principal')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dentro do ministério (menor número aparece primeiro).', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor (Assinatura)')),
                ('imagem', models.ImageField(upload_to='devocionais/', verbose_name='Imagem Ilustrativa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionais',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], unique=True, verbose_name='Dia da Semana')),
                ('resumo', models.CharField(max_length=100, verbose_name='Resumo (ex: Dia de celebração)')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('periodo', models.CharField(max_length=50, verbose_name='Período (ex: 15-17 Julho)')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evento Especial',
                'verbose_name_plural': 'Eventos Especiais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pessoa')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='memorial/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Pessoa do Memorial',
                'verbose_name_plural': 'Pessoas do Memorial',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pastor')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período no Pastorado')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, verbose_name='Descrição Curta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pastores/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Pastor (Histórico)',
                'verbose_name_plural': 'Pastores (Histórico)',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SecaoLideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Seção')),
                ('descricao', models.TextField(blank=True, verbose_name='Texto de Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição na página (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Seção de Liderança',
                'verbose_name_plural': 'Seções de Liderança',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='home.diasemana')),
            ],
            options={
                'verbose_name': 'Evento da Semana',
                'verbose_name_plural': 'Eventos da Semana',
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo ou Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(upload_to='lideranca/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dentro da seção.')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='home.secaolideranca')),
            ],
            options={
                'verbose_name': 'Pessoa da Liderança',
                'verbose_name_plural': 'Pessoas da Liderança',
                'ordering': ['ordem'],
            },
        ),
    ]
